#!/usr/bin/python
# -*- coding=utf-8 -*-

import requests
import chardet
import suds
import config
import sys
import threading
import test
reload(sys)
sys.setdefaultencoding('utf-8')

body1 = u"<BODY><OVINCE_CODE></OVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE></CU_REQUEST_CODE><CUSTOMER></CUSTOMER><BUILDMODENAME></BUILDMODENAME><SITE_NAME></SITE_NAME><SITE_CODE></SITE_CODE><CREATOR></CREATOR><DEMOND_PUT_DATE></DEMOND_PUT_DATE><MDMPROJECTS_NAME></MDMPROJECTS_NAME><DELIVER_TIME></DELIVER_TIME><TUNNEL_BIGIN_POINT></TUNNEL_BIGIN_POINT><TUNNEL_END_POINT></TUNNEL_END_POINT><TUNNEL_ROUT></TUNNEL_ROUT><OPTICAL_BIGIN_POINT></OPTICAL_BIGIN_POINT><OPTICAL_END_POINT></OPTICAL_END_POINT><POLE_BIGIN_POINT></POLE_BIGIN_POINT><POLE_END_POINT></POLE_END_POINT></BODY></PACKET>"

body3 = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><ACCESS_TOKEN></ACCESS_TOKEN><REQUEST_TIME>2017-07-31</REQUEST_TIME></HEAD><BODY><LIST><ELEMENT><REQUEST_TYPE>3</REQUEST_TYPE><REQUEST_TIME>20170802</REQUEST_TIME><PROVINCE_CODE></PROVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE>198805</CU_REQUEST_CODE><CUSTOMER></CUSTOMER><BUILDMODENAME></BUILDMODENAME><SITE_NAME></SITE_NAME><SITE_CODE></SITE_CODE><CREATOR></CREATOR><DEMOND_PUT_DATE>2017-01-01</DEMOND_PUT_DATE><MDMPROJECTS_NAME></MDMPROJECTS_NAME><DELIVER_TIME>20170701</DELIVER_TIME><TUNNEL_BIGIN_POINT></TUNNEL_BIGIN_POINT><TUNNEL_END_POINT></TUNNEL_END_POINT><TUNNEL_ROUT></TUNNEL_ROUT><OPTICAL_BIGIN_POINT></OPTICAL_BIGIN_POINT><OPTICAL_END_POINT></OPTICAL_END_POINT><POLE_BIGIN_POINT></POLE_BIGIN_POINT><POLE_END_POINT></POLE_END_POINT></ELEMENT></LIST></BODY></PACKET>"
body4 = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><ACCESS_TOKEN></ACCESS_TOKEN><REQUEST_TIME>2017-07-31</REQUEST_TIME></HEAD><BODY><REQUEST_TYPE>4</REQUEST_TYPE><REQUEST_TIME>2017-10-10</REQUEST_TIME><PROVINCE_CODE></PROVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE></CU_REQUEST_CODE><CUST_COMPANY></CUST_COMPANY><COMPANY_BATCH></COMPANY_BATCH><SITE_NAME></SITE_NAME><SCENE></SCENE><DELIVERY_TIME></DELIVERY_TIME><LONGITUDE></LONGITUDE><LATITUDE></LATITUDE><SITE_ADDRESS></SITE_ADDRESS><COVER_AREA_FEE></COVER_AREA_FEE><COVER_AREA></COVER_AREA><SYSTEM_NUM></SYSTEM_NUM><BBU_NUM></BBU_NUM><RRU_NUM></RRU_NUM><SYSTEM_TYPE></SYSTEM_TYPE><CREATOR></CREATOR><APPLY_DATE></APPLY_DATE><REMARKS></REMARKS></BODY></PACKET>"
site = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T01_OT_001</SERVICE_CODE><ACCESS_TOKEN>MTAwM2FiY1QwMV9PVF8wMDF4eXoyMDE3LTA4</ACCESS_TOKEN><REQUEST_TIME>2017-07-11 09:00:00</REQUEST_TIME><BATCH_NO>000004</BATCH_NO><TOTAL_NUM>1</TOTAL_NUM><CURRENT_NUM>1</CURRENT_NUM></HEAD><BODY><SITE_CODE>5</SITE_CODE><PROVINCE_CODE>6</PROVINCE_CODE><CITY_CODE>110000</CITY_CODE><CUST_COMPANY>8</CUST_COMPANY><START_TIME>2017-07-05 09:00:00</START_TIME><END_TIME>2017-07-05 09:00:00</END_TIME><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME></BODY></PACKET>"

site1 = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T01_OT_001</SERVICE_CODE><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME><ACCESS_TOKEN>MTAwM2FiY1QwMl9PVF8wMDF4eXoyMDE3LTA4</ACCESS_TOKEN><BATCH_NO>000002</BATCH_NO><TOTAL_NUM>1</TOTAL_NUM><CURRENT_NUM>1</CURRENT_NUM></HEAD><BODY><SITE_CODE>5</SITE_CODE><PROVINCE_CODE>6</PROVINCE_CODE><CITY_CODE>422800</CITY_CODE>  <CUST_COMPANY>8</CUST_COMPANY><START_TIME>2017-07-05 09:00:00</START_TIME><END_TIME>2017-07-05 09:00:00</END_TIME><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME></BODY></PACKET>"

tower = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T01_OT_002</SERVICE_CODE><ACCESS_TOKEN>MTAwM2FiY1QwMV9PVF8wMDJ4eXoyMDE3LTA4</ACCESS_TOKEN><REQUEST_TIME>2017-07-31</REQUEST_TIME><BATCH_NO>000002</BATCH_NO><TOTAL_NUM>1</TOTAL_NUM><CURRENT_NUM>1</CURRENT_NUM></HEAD><BODY><SITE_CODE>5</SITE_CODE><PROVINCE_CODE>6</PROVINCE_CODE><CITY_CODE>120000</CITY_CODE><CUST_COMPANY>8</CUST_COMPANY><START_TIME>2017-07-05 09:00:00</START_TIME><END_TIME>2017-07-05 09:00:00</END_TIME><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME></BODY></PACKET>"

tower1 = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME><ACCESS_TOKEN>MTAwM2FiY1QwMl9PVF8wMDF4eXoyMDE3LTA4</ACCESS_TOKEN><BATCH_NO>000002</BATCH_NO><TOTAL_NUM>4</TOTAL_NUM><CURRENT_NUM>0</CURRENT_NUM></HEAD>  <BODY><SITE_CODE>5</SITE_CODE>  <PROVINCE_CODE>6</PROVINCE_CODE><CITY_CODE>422800</CITY_CODE><CUST_COMPANY>8</CUST_COMPANY><START_TIME>2017-07-05 09:00:00</START_TIME><END_TIME>2017-07-05 09:00:00</END_TIME><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME></BODY></PACKET>"
room = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T01_OT_003</SERVICE_CODE><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME><ACCESS_TOKEN>MTAwM2FiY1QwMV9PVF8wMDN4eXoyMDE3LTA4</ACCESS_TOKEN><BATCH_NO>000002</BATCH_NO><TOTAL_NUM>4</TOTAL_NUM><CURRENT_NUM>0</CURRENT_NUM></HEAD>  <BODY><SITE_CODE>5</SITE_CODE>  <PROVINCE_CODE>6</PROVINCE_CODE><CITY_CODE>422800</CITY_CODE><CUST_COMPANY>8</CUST_COMPANY><START_TIME>2017-07-05 09:00:00</START_TIME><END_TIME>2017-07-05 09:00:00</END_TIME><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME></BODY></PACKET>"

DemandImport = """<PACKET><HEAD><REQUEST_TIME>2017-07-17</REQUEST_TIME><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><ACCESS_TOKEN>MTAwM2FiY1QwMl9PVF8wMDF4eXoyMDE3LTA4</ACCESS_TOKEN></HEAD><BODY><LIST><ELEMENT><REQUEST_TYPE>1</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>370000</PROVINCE_CODE><CITY_CODE>370100</CITY_CODE><COUNTY_CODE>370102</COUNTY_CODE><CU_REQUEST_CODE>370102</CU_REQUEST_CODE><CUST_COMPANY>1003</CUST_COMPANY><COMPANY_BATCH>2017Y01</COMPANY_BATCH><SITE_NAME>需求1</SITE_NAME><SCENE>01</SCENE><DELIVERY_TIME>2017-2-15</DELIVERY_TIME><LONGITUDE>122.123433</LONGITUDE><DIMENSION>33.123433</DIMENSION><COV_AREA_DES>20</COV_AREA_DES><DEV_RADIUS>23</DEV_RADIUS><SYSTEM_NUM>5</SYSTEM_NUM><BAND>sdad</BAND><ANT_HEIGHT>10~12</ANT_HEIGHT><ANT_NUM>2</ANT_NUM><RRU_IS_PULL>1</RRU_IS_PULL><CREATOR>737010115066</CREATOR><DEMOND_PUT_DATE>2017-02-15 00:00:00</DEMOND_PUT_DATE></ELEMENT></LIST></BODY></PACKET>"""

#1	铁塔类	
element = "<ELEMENT><REQUEST_TYPE>1</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>370000</PROVINCE_CODE><CITY_CODE>370100</CITY_CODE><COUNTY_CODE>370102</COUNTY_CODE><CU_REQUEST_CODE>370104</CU_REQUEST_CODE><CUST_COMPANY>1003</CUST_COMPANY><COMPANY_BATCH>2017Y01</COMPANY_BATCH><SITE_NAME>需求1</SITE_NAME><SCENE>01</SCENE><DELIVERY_TIME>2017-2-15</DELIVERY_TIME><LONGITUDE>122.123433</LONGITUDE><DIMENSION>33.123433</DIMENSION><COV_AREA_DES>20</COV_AREA_DES><DEV_RADIUS>23</DEV_RADIUS><SYSTEM_NUM>5</SYSTEM_NUM><BAND>sdad</BAND><ANT_HEIGHT>10~12</ANT_HEIGHT><ANT_NUM>2</ANT_NUM><RRU_IS_PULL>1</RRU_IS_PULL><CREATOR>737010115066</CREATOR><DEMOND_PUT_DATE>2017-02-15 00:00:00</DEMOND_PUT_DATE></ELEMENT>"
#3	传输类
#    element = "<ELEMENT><REQUEST_TYPE>3</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE></PROVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE></CU_REQUEST_CODE><CUSTOMER></CUSTOMER><BUILDMODENAME></BUILDMODENAME><SITE_NAME></SITE_NAME><SITE_CODE></SITE_CODE><CREATOR></CREATOR><DEMOND_PUT_DATE></DEMOND_PUT_DATE><MDMPROJECTS_NAME></MDMPROJECTS_NAME><DELIVER_TIME></DELIVER_TIME><TUNNEL_BIGIN_POINT></TUNNEL_BIGIN_POINT><TUNNEL_END_POINT></TUNNEL_END_POINT><TUNNEL_ROUT></TUNNEL_ROUT><OPTICAL_BIGIN_POINT></OPTICAL_BIGIN_POINT><OPTICAL_END_POINT></OPTICAL_END_POINT><POLE_BIGIN_POINT></POLE_BIGIN_POINT><POLE_END_POINT></POLE_END_POINT></ELEMENT>"
#4	楼宇室分类
#    element = "<ELEMENT><REQUEST_TYPE>4</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>370000</PROVINCE_CODE><CITY_CODE>370102</CITY_CODE><COUNTY_CODE>370102</COUNTY_CODE><CU_REQUEST_CODE>370011</CU_REQUEST_CODE><CUST_COMPANY>1003</CUST_COMPANY><COMPANY_BATCH></COMPANY_BATCH><SITE_NAME></SITE_NAME><SCENE></SCENE><DELIVERY_TIME></DELIVERY_TIME><LONGITUDE></LONGITUDE><LATITUDE></LATITUDE><SITE_ADDRESS></SITE_ADDRESS><COVER_AREA_FEE></COVER_AREA_FEE><COVER_AREA></COVER_AREA><SYSTEM_NUM></SYSTEM_NUM><BBU_NUM></BBU_NUM><RRU_NUM></RRU_NUM><SYSTEM_TYPE></SYSTEM_TYPE><CREATOR></CREATOR><APPLY_DATE></APPLY_DATE><REMARKS></REMARKS></ELEMENT>"
    #5	隧道室分类
#    element = "<ELEMENT><REQUEST_TYPE>1</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE></PROVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE></CU_REQUEST_CODE><CUSTOMER></CUSTOMER><DEMAND_BATCHES></DEMAND_BATCHES><SITE_NAME></SITE_NAME><SCENE></SCENE><DELIVERY_TIME></DELIVERY_TIME><LONGITUDE></LONGITUDE><LATITUDE></LATITUDE><COVER_LENGTH></COVER_LENGTH><SYSTEM_NUM></SYSTEM_NUM><BBU_NUM></BBU_NUM><RRU_NUM></RRU_NUM><SYSTEM_TYPE></SYSTEM_TYPE><CREATOR></CREATOR><DEMOND_PUT_DATE></DEMOND_PUT_DATE><REMARK></REMARK></ELEMENT>" 
DemandImport1 = "<PACKET><HEAD><REQUEST_TIME>2017-07-17</REQUEST_TIME><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><ACCESS_TOKEN>MTAwM2FiY1QwMl9PVF8wMDF4eXoyMDE3LTA4</ACCESS_TOKEN></HEAD><BODY><LIST>"+ element * 1 +"</LIST></BODY></PACKET>"
#T03-T-O-002 需求订单交付验收信息同步服务
dodi = "<PACKET><HEAD><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T03_TO_002</SERVICE_CODE><ACCESS_TOKEN>MTAwM2FiY1QwM19UT18wMDJ4eXoyMDE3LTA4</ACCESS_TOKEN><REQUEST_TIME>2017-07-31</REQUEST_TIME></HEAD><BODY><REQUEST_ID>1217080700015228</REQUEST_ID><REQUEST_TIME></REQUEST_TIME><PRO_NAME>hailong</PRO_NAME><PROVINCE_CODE>34</PROVINCE_CODE><REGION_CODE>340551</REGION_CODE><COUNTY_CODE>340104</COUNTY_CODE><CUST_COMPANY>1003</CUST_COMPANY><BUILD_COMPANY>jianshe</BUILD_COMPANY><DESIGN_COMPANY>sheji</DESIGN_COMPANY><WORKING_COMPANY>shigong</WORKING_COMPANY><SUPERVISOR_COMPANY>jianli</SUPERVISOR_COMPANY><WORKADDRESS></WORKADDRESS><WORKSTARTTIME>2017-07-01</WORKSTARTTIME><WORKENDTIME>2017-08-01</WORKENDTIME><REALITY_DELIVERTIME>2017-09-01</REALITY_DELIVERTIME><DYJPTJ>1</DYJPTJ><SITE_LOC_QK>1</SITE_LOC_QK><HANG_SCOPE>1</HANG_SCOPE><YDDCRL>1</YDDCRL><JWS>1</JWS><KTAZ>1</KTAZ><TDGSFZR>username</TDGSFZR><CHECKTIME>2017-08-08</CHECKTIME><CHECK_PEOPLE>yanshourenyuan</CHECK_PEOPLE></BODY></PACKET>"
#T02-T-O-001 需求承接结果反馈服务 
#T03-T-O-004 批量起租单查询接口
qizhudan = "<PACKET><HEAD><SYS_COMPANY>1004</SYS_COMPANY><SERVICE_CODE>T03_OT_004</SERVICE_CODE><FILE_TYPE>PLQZ</FILE_TYPE><REQUEST_TIME>2017-07-05 09:00:00</REQUEST_TIME><ACCESS_TOKEN>MTAwMmdoaVQwM19PVF8wMDRyc3QyMDE3LTA4</ACCESS_TOKEN><HANDLE_TYPE>2</HANDLE_TYPE><CUST_COMPANY>1002</CUST_COMPANY><ACCOUNT_PERIOD>201704</ACCOUNT_PERIOD><PROVINCE_ID>370000</PROVINCE_ID><CITY_ID>370100</CITY_ID><FLOW_ID>1000156</FLOW_ID><STATUS>1</STATUS></HEAD></PACKET>"

#T03-T-O-006 业务变更确认信息同步接口
#T03-T-O-008 服务终止确认信息同步接口
#T05-T-O-001 详单查询接口
#T05-T-O-002 确认费用清单同步接口
#T05-T-O-003 对账确认单同步接口

def Demand(baowen):
    print u">> 加密"
    print "请求报文明文:\n", baowen
    r0 = requests.post(config.encode, data={'requestXml':baowen})
    endata = r0.content
    print "请求报文密文:\n", endata
    return endata

if __name__ == "__main__":
    for i in range(1):
        t = threading.Thread(target=Demand, args=(DemandImport1,))
        t.start()
    print ">>progarm run end"
