#!/usr/bin/python
# -*- coding=utf-8 -*-

import threading
import time
import requests
import chardet
import suds
import sys
reload(sys)
sys.path.append("/root/git_20170730/kfpt/")
sys.setdefaultencoding('utf-8')
import config
import jiami
import jiemi

def DI1():
    print u">> 需求提交导入服务"
    print "*************"
    token = "MTAwM2FiY1QwMl9PVF8wMDF4eXoyMDE3LTA4"
#    with open("/root/baowen.txt","rb") as f:
#        txt = f.read()
#    print type(txt)
#    print chardet.detect(txt)
#1      铁塔类  
    element = "<ELEMENT><REQUEST_TYPE>1</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>34</PROVINCE_CODE><CITY_CODE>340551</CITY_CODE><COUNTY_CODE>340104</COUNTY_CODE><CU_REQUEST_CODE>370104</CU_REQUEST_CODE><CUST_COMPANY>1003</CUST_COMPANY><COMPANY_BATCH>2017Y01</COMPANY_BATCH><SITE_NAME>需求1"+unichr(25500) * 1 +"</SITE_NAME><SCENE>01</SCENE><DELIVERY_TIME>2017-2-15</DELIVERY_TIME><LONGITUDE>122.123433</LONGITUDE><DIMENSION>33.123433</DIMENSION><COV_AREA_DES>20</COV_AREA_DES><DEV_RADIUS>23</DEV_RADIUS><SYSTEM_NUM>5</SYSTEM_NUM><BAND>sdad</BAND><ANT_HEIGHT>10~12</ANT_HEIGHT><ANT_NUM>2</ANT_NUM><RRU_IS_PULL>1</RRU_IS_PULL><CREATOR>long</CREATOR><DEMOND_PUT_DATE>2017-02-15 00:00:00</DEMOND_PUT_DATE></ELEMENT>"
#3      传输类
#    element = "<ELEMENT><REQUEST_TYPE>3</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>34</PROVINCE_CODE><CITY_CODE>340551</CITY_CODE><COUNTY_CODE>340104</COUNTY_CODE><CU_REQUEST_CODE>1003</CU_REQUEST_CODE><CUSTOMER></CUSTOMER><BUILDMODENAME></BUILDMODENAME><SITE_NAME></SITE_NAME><SITE_CODE></SITE_CODE><CREATOR></CREATOR><DEMOND_PUT_DATE></DEMOND_PUT_DATE><MDMPROJECTS_NAME></MDMPROJECTS_NAME><DELIVER_TIME></DELIVER_TIME><TUNNEL_BIGIN_POINT></TUNNEL_BIGIN_POINT><TUNNEL_END_POINT></TUNNEL_END_POINT><TUNNEL_ROUT></TUNNEL_ROUT><OPTICAL_BIGIN_POINT></OPTICAL_BIGIN_POINT><OPTICAL_END_POINT></OPTICAL_END_POINT><POLE_BIGIN_POINT></POLE_BIGIN_POINT><POLE_END_POINT></POLE_END_POINT></ELEMENT>"
#4      楼宇室分类
#    element = "<ELEMENT><REQUEST_TYPE>4</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE>370000</PROVINCE_CODE><CITY_CODE>370102</CITY_CODE><COUNTY_CODE>370102</COUNTY_CODE><CU_REQUEST_CODE>370011</CU_REQUEST_CODE><CUST_COMPANY>1003</CUST_COMPANY><COMPANY_BATCH></COMPANY_BATCH><SITE_NAME></SITE_NAME><SCENE></SCENE><DELIVERY_TIME></DELIVERY_TIME><LONGITUDE></LONGITUDE><LATITUDE></LATITUDE><SITE_ADDRESS></SITE_ADDRESS><COVER_AREA_FEE></COVER_AREA_FEE><COVER_AREA></COVER_AREA><SYSTEM_NUM></SYSTEM_NUM><BBU_NUM></BBU_NUM><RRU_NUM></RRU_NUM><SYSTEM_TYPE></SYSTEM_TYPE><CREATOR></CREATOR><APPLY_DATE></APPLY_DATE><REMARKS></REMARKS></ELEMENT>"
#5  隧道室分类
#    element = "<ELEMENT><REQUEST_TYPE>1</REQUEST_TYPE><REQUEST_TIME>2017-07-17</REQUEST_TIME><PROVINCE_CODE></PROVINCE_CODE><CITY_CODE></CITY_CODE><COUNTY_CODE></COUNTY_CODE><CU_REQUEST_CODE></CU_REQUEST_CODE><CUSTOMER></CUSTOMER><DEMAND_BATCHES></DEMAND_BATCHES><SITE_NAME></SITE_NAME><SCENE></SCENE><DELIVERY_TIME></DELIVERY_TIME><LONGITUDE>122.123433</LONGITUDE><LATITUDE>22.123433</LATITUDE><COVER_LENGTH></COVER_LENGTH><SYSTEM_NUM></SYSTEM_NUM><BBU_NUM></BBU_NUM><RRU_NUM></RRU_NUM><SYSTEM_TYPE></SYSTEM_TYPE><CREATOR></CREATOR><DEMOND_PUT_DATE></DEMOND_PUT_DATE><REMARK></REMARK></ELEMENT>"
    XML = "<PACKET><HEAD><REQUEST_TIME>2017-07-17</REQUEST_TIME><CUST_COMPANY>1003</CUST_COMPANY><SERVICE_CODE>T02_OT_001</SERVICE_CODE><ACCESS_TOKEN>"+ token +"</ACCESS_TOKEN></HEAD><BODY><LIST>"+ element * 1 +"</LIST></BODY></PACKET>"
    print "请求报文明文:\n", XML
    r0 = requests.post(config.encode, data={'requestXml':XML})
    en = r0.content.replace(r"\n","")[1:-1]        
    u = config.url + "/services/DemandImport?wsdl"
    cc = suds.client.Client(u).service.DemandImport(encReqXml=unichr(10))
    print "请求返回的加密报文:\n", cc
    print ">> 返回报文:\n",jiemi.jiemi(cc.replace(r"\n",""))
    return cc

'''
    person=cc.factory.create('ns0:DemandImport')
    person1=cc.factory.create('ns0:DemandImportResponse')
    person2=cc.factory.create('ns0:Exception')
    print person
    print person1
    print person2
'''

if __name__ == "__main__":
    stime = time.ctime()
    for i in range(1):
        for i in range(1):
            print i
            t = threading.Thread(target=DI1, args=())
            t.start()
        t.join()
    print "start:\r",stime
    print "end:\r", time.ctime()
    print ">> program run end"
